server-port: 30001

db-host: ${PG_HOST:localhost}
db-port: 5432
db-name: evaluation_db
db-schema: customer_schema
db-user: customer_user
db-pass: customer_pass

server:
  port: ${server-port}

spring:
  application:
    name: customer
  flyway:
    baseline-on-migrate: true
  datasource:
    username: ${db-user}
    password: ${db-pass}
    url: jdbc:postgresql://${db-host}:${db-port}/${db-name}?currentSchema=${db-schema}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

