apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit
  labels:
    app: credit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-app
  template:
    metadata:
      labels:
        app: credit-app
    spec:
      containers:
        - name: credit
          imagePullPolicy: Never
          image: credit-img:latest
          ports:
            - containerPort: 30000
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url

---
apiVersion: v1
kind: Service
metadata:
  name: credit-service
spec:
  type: NodePort
  selector:
    app: credit-app
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000

