apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
data:
  customer-url: customer-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer
          imagePullPolicy: Never
          image: customer-img:latest
          ports:
            - containerPort: 30001
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-app
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001

