apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  product-url: product-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product
          imagePullPolicy: Never
          image: product-img:latest
          ports:
            - containerPort: 30002
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-app
  ports:
    - port: 30002
      targetPort: 30002

