server-port: 37002

db-host: localhost
db-port: 5432
db-name: product_db
db-user: product_user
db-pass: product_pass

server:
  port: ${server-port}

spring:
  application:
    name: evaluation-customer
  flyway:
    baseline-on-migrate: true
  datasource:
    username: ${db-user}
    password: ${db-pass}
    url: jdbc:postgresql://${db-host}:${db-port}/${db-name}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

