server-port: 37000
customer-service-port: 37001
product-service-port: 37002

db-host: localhost
db-port: 5432
db-name: postgres
db-schema: credit_schem
db-user: credit_user
db-pass: credit_pass

server:
  port: ${server-port}

spring:
  application:
    name: evaluation-credit
  flyway:
    baseline-on-migrate: true
  datasource:
    username: ${db-user}
    password: ${db-pass}
    url: jdbc:postgresql://${db-host}:${db-port}/${db-name}?currentSchema=${db-schema}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

connect-timeout: 10000
read-timeout: 10000
customer-service-url: http://localhost:${customer-service-port}
product-service-url: http://localhost:${product-service-port}
